// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace pizzaDeliveryApp
{
	public partial class ProductCountLessViewController : NSViewController
	{
		public ProductCountLessViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
