// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace pizzaDeliveryApp
{
	public partial class ProductAddedViewController : NSViewController
	{
		public ProductAddedViewController (IntPtr handle) : base (handle)
		{
		}

        partial void closeClicked(NSButton sender)
        {
            DismissViewController(this);
        }

    }
}
