// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace DBApp
{
	public partial class MainMenuViewController : NSViewController
	{
		public MainMenuViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
